add find_apernames function
spacetelescope/pysiaf pull request #355
Opened 2024-10-25 13:25 UTC by mperrin

This PR adds a small utility method `find_apernames` to ease lookup of a particular aperture name by a given substring. I often find myself not quite remembering the precise name of a given aperture, and it's tedious to look through the long list of all apernames. Hence this function.  I figure this little tool may be useful to others as well. 

![Screenshot 2024-10-25 at 9 24 18 AM](https://github.com/user-attachments/assets/9ca783e1-8ae2-4d83-b06c-e41e57278263)

2025-04-23 13:54 UTC, mperrin commented
@tonysohn @mfixstsci by the way here is another small PR I made 6 months ago, which it doesn't look like anyone has looked at yet. A tiny addition but it may be useful to others...

2025-04-23 18:56 UTC, tonysohn commented
Tested and works as intended. Looks like the documentation has been added, too. I approve (although, I can't formally approve with the button).

2025-04-24 14:15 UTC, mperrin commented
Thanks @tonysohn. Out of curiosity, if you don't have write access here to approve PRs, then who does? Is it only @mfixstsci? And perhaps @Witchblade101 ?

2025-04-24 14:17 UTC, tonysohn approved these changes
Changes approved.

2025-04-24 14:18 UTC, tonysohn commented
> Thanks @tonysohn. Out of curiosity, if you don't have write access here to approve PRs, then who does? Is it only @mfixstsci? And perhaps @Witchblade101 ?

I was able to add myself as one of the reviewers, which let me approve the PR.

2025-04-24 14:25 UTC, tonysohn commented
> Ah never mind my last query! It looks like you were approving it right at the exact same time I was asking that!

I actually approved it after seeing your question above :-)

2025-04-24 14:36 UTC, mfixstsci commented
Hey Guys -- Looks good to me @mperrin and thank you for adding to the docs.

2025-04-24 14:36 UTC, merged

2025-04-24 14:44 UTC, Witchblade101 requested changes
> In [1]: import pysiaf
>In [2]: siaf = pysiaf.Siaf('MIRI')
>In [3]: print(len(siaf.apernames))
>281
>
>In [4]: siaf.find_apernames('lrs')
>Out[4]: []
>
>In [5]: siaf.find_apernames('mrs')
>Out[5]: []
>
>In [6]: siaf.find_apernames('LRS')
>Out[6]: ['MIRIM_TALRS']

Add the upper() method, so the search will still work even if a user enters the string in lowercase:

`return [name for name in self.apernames if substring.upper() in name]`

>In [1]: import pysiaf
>In [2]: siaf = pysiaf.Siaf('miri')
>In [3]: siaf.find_apernames('lrs')
>Out[3]: ['MIRIM_TALRS']

2025-04-24 14:45 UTC, Witchblade101 commented
Ack! I guess it got approved and merged while I was testing. :p

2025-04-24 14:51 UTC, mfixstsci commented
> Ack! I guess it got approved and merged while I was testing. :p

Sorry Doug! I saw the approval and figured we should move on this since it's been sitting for a while. I will make sure to coordinate with you first next time!

2025-04-24 14:55 UTC, Witchblade101 commented
I'll open a new issue and add my proposed fix there.